apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvat-postgres-data
  namespace: cvat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 20Gi

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: efs-claim
#   namespace: cvat
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: efs-sc
#   resources:
#     requests:
#       storage: 5Gi