apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvat-frontend
  namespace: cvat
  labels:
    app: cvat-app
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cvat-app
      tier: frontend
  template:
    metadata:
      labels:
        app: cvat-app
        tier: frontend
    spec:
      containers:
        - name: cvat-frontend-app-container
          image: 143743236805.dkr.ecr.eu-west-1.amazonaws.com/cvat-frontend:acd5ef7c97f442226153bca769c461b2736819eb
          imagePullPolicy: Always
          env:
          - name: REACT_APP_API_PROTOCOL
            value: "http"
          - name: REACT_APP_API_HOST
            value: "{MY_SERVER_URL.com}" # Is set in build process, needs to be moved to
          - name: REACT_APP_API_PORT
            value: "8080"
          - name: FOR_GODS_SAKE_PLEASE_REDEPLOY          # This is important
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD' # This is important
          ports:
          - containerPort: 80
          resources: {}
